plugins {
    id "com.android.application"
}

android {
    namespace "app.buyme.shopmanager"
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "app.buyme.shopmanager"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "1.2"
    }
}

dependencies {
    implementation "androidx.browser:browser:1.8.0"
}